### PR TITLE
[5.1] KREG-3: Add optional from softphone (TeamMate) to MS Teams migration mechanism

### PR DESCRIPTION
**Pull request by harenson**
Depends on:
- https://github.com/2600hz/kazoo-crossbar/pull/378
- https://github.com/2600hz/kazoo-core/pull/527

Back-port of https://github.com/2600hz/kazoo-registrar/pull/16

When a REGISTER request is received from a MS Teams integration (TeamMate) device and the credentials used belong to a softphone device:

If `registrar.migrate_softphone_to_ms_teams=true`, the device will be migrated from softphone into a proper teammate device. The registration process will continue after the migration succeeds.

Else, if REGISTER request's User-Agent matches any of the `registrar.integrations_user_agent_regexes` list, registration will be forbidden.

### CODE REVIEW

**Review by icehess — APPROVED** [review]
lgtm

**Comment by icehess** [comment]
FYI those PR has been reverted. @harenson please create new PRs for them again and wait until we are ready to merge new features again.

**Comment by harenson** [comment]
@icehess Ok, thank you for the heads up. The reverted PRs have been re-opened. Find the new PRs in this PR's description.

**Review by lazedo — CHANGES_REQUESTED** [review]
msteams has nothing to do with registrar

**Comment by harenson** [comment]
@lazedo This is just a back-port PR. There are a couple of PRs (https://github.com/2600hz/kazoo-registrar/pull/20 and https://github.com/2600hz/kazoo-core/pull/534) that take care of moving migration process from registrar application to core/kazoo_endpoint application. Once those PRs get merged into master, I will also back-port those.

**Comment by lazedo** [comment]
you should close this and reopen when the `master` changes are done

**Comment by harenson** [comment]
@lazedo Makes sense. I will just move the PR to draft and mark as ready for review again once updated.

**Pull request merged**
